/*
 * generated by Xtext 2.12.0
 */
package org.upct.tr


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TRStandaloneSetup extends TRStandaloneSetupGenerated {

	def static void doSetup() {
		new TRStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
